database:
    image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
        - "5405:5432"
    environment:
        POSTGRES_PASSWORD: insecure
        POSTGRES_DB: atlas
        POSTGRES_USER: atlas

elasticsearch:
    image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
       - "9200:9200"
       - "9300:9300"

web:
    build: ./web
    ports:
        - "8101:8000"
    links:
        - database:database
        - elasticsearch:elasticsearch

