version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    ports:
       - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: insecure
      POSTGRES_PASSWORD: insecure
    volumes:
       - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    extra_hosts:
      admin.data.amsterdam.nl: 10.243.16.4
  web:
      build: ./web
      ports:
        - "8022:8000"
      volumes:
        - "./web/geosearch:/app"
      environment:
        - UWSGI_HTTP=0.0.0.0:8000
        - UWSGI_STATS=0.0.0.0:9191
        - UWSGI_MODULE=wsgi
        - UWSGI_CALLABLE=app
        - UWSGI_MASTER=1
        - UWSGI_MASTER=4
        - BAG_V11_DB_USER_OVERRIDE=insecure
        - NAP_DB_USER_OVERRIDE=insecure
        - MILIEUTHEMAS_DB_USER_OVERRIDE=insecure
        - MONUMENTEN_DB_USER_OVERRIDE=insecure
        - VARIOUS_SMALL_DATASETS_DB_USER_OVERRIDE=insecure
        - DATASERVICES_DB_USER_OVERRIDE=insecure
        - BAG_V11_DB_PASSWORD_OVERRIDE=insecure
        - NAP_DB_PASSWORD_OVERRIDE=insecure
        - MILIEUTHEMAS_DB_PASSWORD_OVERRIDE=insecure
        - MONUMENTEN_DB_PASSWORD_OVERRIDE=insecure
        - VARIOUS_SMALL_DATASETS_DB_PASSWORD_OVERRIDE=insecure
        - DATASERVICES_DB_PASSWORD_OVERRIDE=insecure
        - BAG_V11_DB_HOST_OVERRIDE=database
        - NAP_DB_HOST_OVERRIDE=database
        - MILIEUTHEMAS_DB_HOST_OVERRIDE=database
        - MONUMENTEN_DB_HOST_OVERRIDE=database
        - VARIOUS_SMALL_DATASETS_DB_HOST_OVERRIDE=database
        - DATASERVICES_DB_HOST_OVERRIDE=database