version: '3.0'
services:
  bag_db:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bag
      POSTGRES_USER: bag
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  nap_db:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: nap
      POSTGRES_USER: nap
      POSTGRES_PASSWORD: insecure
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  milieuthemas_db:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  monumenten_db:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5412:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: monumenten
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  tellus_db:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: tellus
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  web:
      build: ./web
      ports:
        - "8022:8000"
      environment:
        - CONSUL_HOST=${CONSUL_HOST:-notset}
        - CONSUL_PORT=${CONSUL_PORT:-8500}
        - UWSGI_HTTP=0.0.0.0:8000
        - UWSGI_STATS=0.0.0.0:9191
        - UWSGI_MODULE=wsgi
        - UWSGI_CALLABLE=app
        - UWSGI_MASTER=1
        - UWSGI_MASTER=4
