services:
  database:
    image: postgis/postgis:14-3.2
    restart: always
    user: postgres
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    ports:
      - "5415:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insecure
    command: [ "postgres", "-c", "log_statement=all" ]
  web:
    build:
      context: .
    ports:
      - "8097:8000"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      UWSGI_STATIC_MAP: "/geosearch/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:insecure@database/dataservices}"
      CORS_ALLOW_ALL_ORIGINS: "${CORS_ALLOW_ALL_ORIGINS:-true}"
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL:-INFO}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      AUDIT_LOG_LEVEL: "${AUDIT_LOG_LEVEL:-INFO}"
      AZURE_APPI_AUDIT_CONNECTION_STRING: "${AZURE_APPI_AUDIT_CONNECTION_STRING:-}"
      AZURE_APPI_CONNECTION_STRING: "${AZURE_APPI_CONNECTION_STRING:-}"
      # Generated using: jq -c < src/jwks_test.json
      PUB_JWKS: '{"keys":[{"kty":"EC","key_ops":["verify","sign"],"kid":"2aedafba-8170-4064-b704-ce92b7c89cc6","crv":"P-256","x":"6r8PYwqfZbq_QzoMA4tzJJsYUIIXdeyPA27qTgEJCDw=","y":"Cf2clfAfFuuCB06NMfIat9ultkMyrMQO9Hd2H7O9ZVE=","d":"N1vu0UQUp0vLfaNeM0EDbl4quvvL6m_ltjoAXXzkI3U="}]}'
      OAUTH_JWKS_URL: "${OAUTH_JWKS_URL}"
      CLOUD_ENV: "${CLOUD_ENV:-local}"
      DJANGO_DEBUG: 1
      INITIALIZE_DB: "${INITIALIZE_DB:-true}"
    command: >
      /bin/bash -c "uv run uvicorn geosearch.asgi:application --host 0.0.0.0 --reload"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml
        - action: sync+restart
          path: ./src/geosearch/settings.py
          target: /app/src/geosearch/settings.py
