# Compose file used for testing in CI
version: '3.0'
services:
  bag_v11_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bag_v11
      POSTGRES_USER: bag_v11
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  nap_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: nap
      POSTGRES_USER: nap
      POSTGRES_PASSWORD: insecure
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  milieuthemas_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  monumenten_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: monumenten
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  various_small_datasets_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: various_small_datasets
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  dataservices_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: dataservices
      OS_TENANT_ID: ${OS_TENANT_ID}
      OS_AUTH_TOKEN: ${OS_AUTH_TOKEN}
    volumes:
        - "../db-scripts/download-db.sh:/bin/download-db.sh"  # Make CI download the test fixtures
  web_test:
    build: ../web
    environment:
      - BAG_V11_DB_USER_OVERRIDE=bag_v11
      - NAP_DB_USER_OVERRIDE=nap
      - MILIEUTHEMAS_DB_USER_OVERRIDE=milieuthemas
      - MONUMENTEN_DB_USER_OVERRIDE=monumenten
      - VARIOUS_SMALL_DATASETS_DB_USER_OVERRIDE=various_small_datasets
      - DATASERVICES_DB_USER_OVERRIDE=dataservices
      - BAG_V11_DB_PASSWORD_OVERRIDE=insecure
      - NAP_DB_PASSWORD_OVERRIDE=insecure
      - MILIEUTHEMAS_DB_PASSWORD_OVERRIDE=insecure
      - MONUMENTEN_DB_PASSWORD_OVERRIDE=insecure
      - VARIOUS_SMALL_DATASETS_DB_PASSWORD_OVERRIDE=insecure
      - DATASERVICES_DB_PASSWORD_OVERRIDE=insecure
      - BAG_V11_DB_HOST_OVERRIDE=bag_v11_db
      - NAP_DB_HOST_OVERRIDE=nap_db
      - MILIEUTHEMAS_DB_HOST_OVERRIDE=milieuthemas_db
      - MONUMENTEN_DB_HOST_OVERRIDE=monumenten_db
      - VARIOUS_SMALL_DATASETS_DB_HOST_OVERRIDE=various_small_datasets_db
      - DATASERVICES_DB_HOST_OVERRIDE=dataservices_db