version: '3.0'
services:
  bag_v11_db:
    image: amsterdam/postgres11
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bag_v11
      POSTGRES_USER: bag_v11
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  nap_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: nap
      POSTGRES_USER: nap
      POSTGRES_PASSWORD: insecure
  milieuthemas_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: milieuthemas
#  tellus_db:
#    image: amsterdam/postgres11
#    environment:
#      POSTGRES_PASSWORD: insecure
#      POSTGRES_USER: tellus
  monumenten_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: monumenten
  various_small_datasets_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: various_small_datasets
  dataservices_db:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: dataservices
  web_test:
    build: ../web
    command: python test_dataset.py
