version: '3.0'
services:
  bag_db:
    image: amsterdam/postgres11
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bag
      POSTGRES_USER: bag
  nap_db:
    image: amsterdam/postgres11
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: nap
      POSTGRES_USER: nap
      POSTGRES_PASSWORD: insecure
  milieuthemas_db:
      image: amsterdam/postgres11
      ports:
        - "5402:5432"
      environment:
        POSTGRES_PASSWORD: insecure
        POSTGRES_USER: milieuthemas
#  tellus_db:
#      image: amsterdam/postgres11
#      ports:
#        - "5409:5432"
#      environment:
#        POSTGRES_PASSWORD: insecure
#        POSTGRES_USER: tellus
  monumenten_db:
      image: amsterdam/postgres11
      ports:
        - "5412:5432"
      environment:
        POSTGRES_PASSWORD: insecure
        POSTGRES_USER: monumenten
  grondexploitatie_db:
      image: amsterdam/postgres11
      ports:
        - "5404:5432"
      environment:
        POSTGRES_PASSWORD: insecure
        POSTGRES_USER: grondexploitatie
  various_small_datasets_db:
      image: amsterdam/postgres11
      ports:
        - "5408:5432"
      environment:
        POSTGRES_PASSWORD: insecure
        POSTGRES_USER: various_small_datasets
  web_test:
    build: ../web
    command: python test_dataset.py
